joern_path: "C://Users//simon//joern" # Where is your joern installation?
export_path: C://Users//simon//myproject//export" # Where did you export your cpg from joern?

neo4j_uri: "bolt://localhost:7687"
neo4j_user: "neo4j"
neo4j_password: "password"

neo4j_import_path: C://Users//simon//.Neo4jDesktop//relate-data//dbmss//dbms-1f1b1b1b-1b1b-1b1b-1b1b-1b1b1b1b1b1b//import"
# Neo4j import folder is specific to the database. Data from the export_path will be copied to this folder. To get the import folder, run the following query in neo4j:
########
# CALL dbms.listConfig() YIELD name, value
# WHERE name='dbms.directories.import'
# RETURN value
########
# from https://community.neo4j.com/t5/neo4j-graph-platform/how-to-get-location-of-neo4j-imports-folder-of-a-db/m-p/49579
# TODO: Find a way to get this automatically
